# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8100fe17124bf253b76a702c16ae0910055c7b39a9536ccb310c6071307489e0fd7225cea401969b302de6a11351af16f114a4acb99aa0a6594c7a178de6e309

test:
  secret_key_base: 7eaafecc031e908159771831eb72acbac5fd21df1ece18888262cc914a5a1f109766d8f632c59413a4e1652a7788f08e41855bbd27b6a0d44865b768fd64a176

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
